server:
  port: 8040
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anyingcccsoft/springcloud/
          search-paths: cccsoft-config-repo
          username:
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/